//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projectoree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROFILE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROFILE()
        {
            this.LISTINGS = new HashSet<LISTING>();
            this.EXPERIENCEs = new HashSet<EXPERIENCE>();
        }
    
        public string userid { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        public string discipline { get; set; }
        public Nullable<long> contactnumber { get; set; }
        public string skills { get; set; }
        public string units { get; set; }
        public string interests { get; set; }
        public string bio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LISTING> LISTINGS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXPERIENCE> EXPERIENCEs { get; set; }
    }
}
